### ISSUE TITLE
JS8500

### ISSUE THREAD

**Issue by pitoganzado** [sermayoral/ha-samsungtv-encrypted#38]
Hi to all :)
JS8500 only the power on and off doesn't work, all the rest so far, so good.
Thank you!

**Comment by sermayoral** [comment]
Power on does not work on encrypted TVs.

For powering off in your model, you have to define the 'key_power_off' custom variable, as explained in: https://github.com/sermayoral/ha-samsungtv-encrypted#custom-variables

Probably it works in your TV model in that way:
```
media_player:
  - platform: samsungtv_encrypted
    host: IP_ADDRESS
    token: TOKEN
    sessionid: SESSION_ID
    port: 8080
    name: Whatever
    key_power_off: KEY_POWER
```
