### ISSUE TITLE
turn_on_action not working

### ISSUE THREAD

**Issue by vlumikero** [sermayoral/ha-samsungtv-encrypted#48]
Hi,

I can't get the turn_on_action to work. I looked at your code and I can't figure out why it wouldn't.

Here's my config:

```
media_player:
  - platform: samsungtv_encrypted
    host: 192.168.1.177
    token: xxx
    sessionid: 1
    port: 8080
    turn_on_action:
      service: switch.turn_on
      entity_id: switch.samsung_tv
```

And this is the error message:
```
Invalid config for [media_player.samsungtv_encrypted]: [turn_on_action] is an invalid option for [media_player.samsungtv_encrypted]. Check: media_player.samsungtv_encrypted->turn_on_action.
 ```
