### ISSUE TITLE
Is there a way to edit sources list?

### ISSUE THREAD

**Issue by photonforge** [sermayoral/ha-samsungtv-encrypted#7]
only 2 sources are listed in the dropdown. Is it  possible to edit sources and add HDMI 1, HDMI 2 etc?

**Comment by sermayoral** [comment]
Here is an example:
```
media_player:
  - platform: samsungtv_custom
    host: IP_ADDRESS
    mac: MAC_ADDRESS
    port: (8001 or 8002)
    sourcelist: '{"PlayStation": "KEY_HDMI1", "RaspberryPi": "KEY_HDMI2", "Chromecast": "KEY_HDMI3"}'
```
I'm working in a method using uPNP of sources autodiscovering. I hope it will be ready soon.
