### ISSUE TITLE
Requests: Change name

### ISSUE THREAD

**Issue by asiersan** [sermayoral/ha-samsungtv-encrypted#8]
Would be posible to change the name from Samsung remote to any desired tv name. With a confing setting???

**Comment by sermayoral** [comment]
You can do it. As README says:

"Note: This is the same as the configuration for the built-in Samsung Smart TV component, except for the custom variables."

So:

Configuration Variables

host

    (string)(Required)

    The hostname or IP of the Samsung Smart TV, e.g., 192.168.0.10.

name

    (string)(Optional)

    The name you would like to give to the Samsung Smart TV.

Here is an example defining a name: 

```
media_player:
  - platform: samsungtv_encrypted
    name: Kitchen TV
    host: !secret ip_samsung_tv
    token: !secret token_samsung_tv
    sessionid: !secret sessionid_samsung_tv
    port: 8080
```
