### ISSUE TITLE
Question: Play to youtube app

### ISSUE THREAD

**Issue by pergolafabio** [sermayoral/ha-samsungtv-encrypted#80]
Hi
question, i also have an older H serie, can i use this component to play media on the "youtube" app thats present on the samsung tv?

For example, if i open youtube on a chromebrowser, my notebook recognizes the samsung tv as some kind of media device , and i can cast the youtube link to the youtube app on the TV

thnx for answering

**Comment by sermayoral** [comment]
@pergolafabio sorry. It does not work with this version

**Comment by pergolafabio** [comment]
Oh, no other workaround? I have found some rest command, it actually start/open the YouTube app, but then I get "video not found"

```
rest_command:
  play_youtube_onsamsungtv:
    url: 'http://IPADDRESSOFTV:8080/ws/apps/YouTube'
    method: post
    content_type: 'text/plain'
    payload: 'v=3QBKtijv2sk'
```

![image](https://user-images.githubusercontent.com/43251136/142157831-ab109634-451f-4151-9374-2c30f798f100.png)
