### ISSUE TITLE
Running script requires passing in a context

### ISSUE THREAD

**Issue by Enzokot** [sermayoral/ha-samsungtv-encrypted#82]
When i execute `turn_on` service for TV this warning appears:
```
Logger: homeassistant.helpers.script.samsung_tv_remote
Source: helpers/script.py:1365
First occurred: 15:05:42 (2 occurrences)
Last logged: 15:06:34

Samsung TV Remote: Running script requires passing in a context
```
Configuration:
```
 - platform: samsungtv_encrypted 
   host: 192.168.217.83 
   token: !secret samsungtv_kit_token 
   sessionid: 1 
   port: 8080
   turn_on_action:
     - condition: and
       conditions:
         - condition: template
           value_template: "{{ states('media_player.samsung_tv_remote') in ['off', 'unknown', 'unavailable'] }}"
     - service: esphome.perenio_petra01_kitchen_send_samsung_command
       data:
         data: '0xE0E040BF'
```
